# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pro.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpro.proto\"\xfd\x06\n\x0e\x45xampleMessage\x12\x13\n\x06\x66ield1\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x13\n\x06\x66ield2\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x13\n\x06\x66ield3\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x13\n\x06\x66ield4\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x13\n\x06\x66ield5\x18\x05 \x01(\rH\x04\x88\x01\x01\x12\x13\n\x06\x66ield6\x18\x06 \x01(\rH\x05\x88\x01\x01\x12\x13\n\x06\x66ield7\x18\x07 \x01(\tH\x06\x88\x01\x01\x12+\n\x06\x66ield8\x18\x08 \x01(\x0b\x32\x1b.ExampleMessage.SubMessage1\x12\x0e\n\x06\x66ield9\x18\t \x01(\t\x12\x0f\n\x07\x66ield10\x18\x0b \x01(\t\x12\x32\n\x07\x66ield15\x18\x0f \x03(\x0b\x32!.ExampleMessage.Field15SubMessage\x12\x0f\n\x07\x66ield18\x18\x12 \x01(\r\x12\x0f\n\x07\x66ield21\x18\x15 \x01(\t\x12\x0f\n\x07\x66ield22\x18\x16 \x01(\t\x12\x0f\n\x07\x66ield23\x18\x17 \x01(\t\x12\x0f\n\x07\x66ield24\x18\x18 \x01(\t\x12\x0f\n\x07\x66ield25\x18\x19 \x01(\t\x1a\xed\x02\n\x0bSubMessage1\x12\x38\n\x06\x66ield1\x18\x64 \x01(\x0b\x32(.ExampleMessage.SubMessage1.SubMessage11\x1a\xa3\x02\n\x0cSubMessage11\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\r\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x04\x12\x0e\n\x06\x66ield4\x18\x04 \x01(\t\x12I\n\x06\x66ield5\x18\x05 \x03(\x0b\x32\x39.ExampleMessage.SubMessage1.SubMessage11.Field5SubMessage\x12\x0e\n\x06\x66ield6\x18\x06 \x01(\r\x12\x0e\n\x06\x66ield7\x18\x07 \x01(\t\x12\x0e\n\x06\x66ield8\x18\x08 \x01(\t\x1aX\n\x10\x46ield5SubMessage\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x13\n\tstr_value\x18\x02 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_value\x18\x03 \x01(\x0cH\x00\x42\x08\n\x06\x66ield2\x1a\x33\n\x11\x46ield15SubMessage\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\t\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\tB\t\n\x07_field1B\t\n\x07_field2B\t\n\x07_field3B\t\n\x07_field4B\t\n\x07_field5B\t\n\x07_field6B\t\n\x07_field7b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pro_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXAMPLEMESSAGE']._serialized_start=14
  _globals['_EXAMPLEMESSAGE']._serialized_end=907
  _globals['_EXAMPLEMESSAGE_SUBMESSAGE1']._serialized_start=412
  _globals['_EXAMPLEMESSAGE_SUBMESSAGE1']._serialized_end=777
  _globals['_EXAMPLEMESSAGE_SUBMESSAGE1_SUBMESSAGE11']._serialized_start=486
  _globals['_EXAMPLEMESSAGE_SUBMESSAGE1_SUBMESSAGE11']._serialized_end=777
  _globals['_EXAMPLEMESSAGE_SUBMESSAGE1_SUBMESSAGE11_FIELD5SUBMESSAGE']._serialized_start=689
  _globals['_EXAMPLEMESSAGE_SUBMESSAGE1_SUBMESSAGE11_FIELD5SUBMESSAGE']._serialized_end=777
  _globals['_EXAMPLEMESSAGE_FIELD15SUBMESSAGE']._serialized_start=779
  _globals['_EXAMPLEMESSAGE_FIELD15SUBMESSAGE']._serialized_end=830
# @@protoc_insertion_point(module_scope)
